In [1]:
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, plot_confusion_matrix,accuracy_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn import datasets
from keras.models import Sequential, Model
from keras.layers import Input, Dense
from keras.layers import Dropout
from sklearn import metrics

import pydot

import numpy as np
import seaborn as sns

In [2]:
pulsar_df = pd.read_csv('https://raw.githubusercontent.com/g-roger/deep-learning/master/projeto-final/datasets/pulsar_data_train.csv')

In [3]:
pulsar_df.astype({'target_class': 'int32'}).dtypes

 Mean of the integrated profile                  float64
 Standard deviation of the integrated profile    float64
 Excess kurtosis of the integrated profile       float64
 Skewness of the integrated profile              float64
 Mean of the DM-SNR curve                        float64
 Standard deviation of the DM-SNR curve          float64
 Excess kurtosis of the DM-SNR curve             float64
 Skewness of the DM-SNR curve                    float64
target_class                                       int32
dtype: object

In [4]:
pulsar_df['target'] = pulsar_df['target_class'].apply(np.int64)

In [5]:
pulsar_df

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class,target
0,121.156250,48.372971,0.375485,-0.013165,3.168896,18.399367,7.449874,65.159298,0.0,0
1,76.968750,36.175557,0.712898,3.388719,2.399666,17.570997,9.414652,102.722975,0.0,0
2,130.585938,53.229534,0.133408,-0.297242,2.743311,22.362553,8.508364,74.031324,0.0,0
3,156.398438,48.865942,-0.215989,-0.171294,17.471572,NaN,2.958066,7.197842,0.0,0
4,84.804688,36.117659,0.825013,3.274125,2.790134,20.618009,8.405008,76.291128,0.0,0
...,...,...,...,...,...,...,...,...,...,...
12523,124.312500,53.179053,-0.012418,-0.556021,7.186455,29.308266,4.531382,21.725143,0.0,0
12524,115.617188,46.784600,0.218177,0.226757,6.140468,NaN,5.732201,34.357283,0.0,0
12525,116.031250,43.213846,0.663456,0.433088,0.785117,11.628149,17.055215,312.204325,0.0,0
12526,135.664062,49.933749,-0.089940,-0.226726,3.859532,21.501505,7.398395,62.334018,0.0,0
12527,120.726562,50.472256,0.346178,0.184797,0.769231,11.792603,17.662222,329.548016,0.0,0

In [6]:
pulsar_df.drop(columns=['target_class'], inplace=True)
pulsar_df.dropna()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target
0,121.156250,48.372971,0.375485,-0.013165,3.168896,18.399367,7.449874,65.159298,0
1,76.968750,36.175557,0.712898,3.388719,2.399666,17.570997,9.414652,102.722975,0
2,130.585938,53.229534,0.133408,-0.297242,2.743311,22.362553,8.508364,74.031324,0
4,84.804688,36.117659,0.825013,3.274125,2.790134,20.618009,8.405008,76.291128,0
7,109.406250,55.912521,0.565106,0.056247,2.797659,19.496527,9.443282,97.374578,0
...,...,...,...,...,...,...,...,...,...
12522,124.828125,50.586731,0.233563,-0.286908,2.342809,13.949966,9.226188,117.308146,0
12523,124.312500,53.179053,-0.012418,-0.556021,7.186455,29.308266,4.531382,21.725143,0
12525,116.031250,43.213846,0.663456,0.433088,0.785117,11.628149,17.055215,312.204325,0
12526,135.664062,49.933749,-0.089940,-0.226726,3.859532,21.501505,7.398395,62.334018,0
12527,120.726562,50.472256,0.346178,0.184797,0.769231,11.792603,17.662222,329.548016,0

In [7]:
# Normalização

X=pulsar_df.drop(['target'],axis=1)
y=pulsar_df['target']
X=StandardScaler().fit_transform(X)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)

In [9]:
# Criação de rede MLP com KERAS
#Modelo da Rede MLP

model = Sequential()
model.add(Dense(10, input_dim = X_train.shape[1], activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(8, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation = 'sigmoid'))

In [10]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
history = model.fit(X_train, y_train, epochs=10, batch_size=80)

Epoch 1/10
110/110 [==============================] - 2s 4ms/step - loss: nan - accuracy: 0.9046
Epoch 2/10
110/110 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.9088
Epoch 3/10
110/110 [==============================] - 1s 6ms/step - loss: nan - accuracy: 0.9088
Epoch 4/10
110/110 [==============================] - 1s 5ms/step - loss: nan - accuracy: 0.9088
Epoch 5/10
110/110 [==============================] - 1s 5ms/step - loss: nan - accuracy: 0.9088
Epoch 6/10
110/110 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.9088
Epoch 7/10
110/110 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.9088
Epoch 8/10
110/110 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.9088
Epoch 9/10
110/110 [==============================] - 1s 5ms/step - loss: nan - accuracy: 0.9088
Epoch 10/10
110/110 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.9088

In [12]:
scores = model.evaluate(X_test, y_test)

118/118 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.9061